- name: deploy ubuntu
  include: ubuntu-1.yaml
  when: ansible_os_family == 'Debian'

- name: deploy Centos
  include: Centos-1.yaml
  when: ansible_os_family == 'RedHat'
- name: Creates directory ubuntu
  file:
    path: "{{ default_home_ubuntu }}"
    state: directory
- name: Creates directory Centos
  file:
    path: "{{ default_home_centos }}"
    state: directory
- name: html to ubuntu
  copy:
    src: index.html
    dest: "{{ default_home_ubuntu }}"
  when: ansible_os_family == 'Debian'
- name: html to Centos
  copy:
    src: index.html
    dest: "{{ default_home_centos }}"
  when: ansible_os_family == 'RedHat'
- name: Templates
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    backup: yes
  become: yes
  tags:
    - template
- name: Test 80 port
  wait_for:
    host: localhost
    port: 80
    state: started
  tags:
    - test1
- name: Test 80 port
  uri:
    url: http://localhost
    return_content: yes
  register: this
  failed_when: "'comrates' not in this.content "
  tags:
    - test
- debug:
    msg: "{{ this.status }}"
  tags:
    - test2
